# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0002_auto_20170103_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='show_all',
            field=models.BooleanField(default=False),
        ),
    ]
