# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0003_answer_show_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_reply_input',
            field=models.BooleanField(default=False),
        ),
    ]
