# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0004_comment_comment_reply_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_comments', to='site_page.Answer'),
        ),
    ]
