# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0005_auto_20170104_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='show_all',
            new_name='show_all_comments',
        ),
        migrations.AddField(
            model_name='answer',
            name='show_all_content',
            field=models.BooleanField(default=False),
        ),
    ]
