# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0006_auto_20170105_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
