# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0007_auto_20170112_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_vote',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_vote_answer', to='site_page.UserProfile'),
        ),
    ]
