# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0008_answer_user_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='show_all_comments',
        ),
    ]
