# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0009_remove_answer_show_all_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
