# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0010_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=True, max_length=128, null=True),
        ),
    ]
