# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0020_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
