# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0021_answer_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
