# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0022_auto_20170410_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='like_or',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
