# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0023_auto_20170411_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
