# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0024_auto_20170411_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='like_or',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
