# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0025_answer_like_or'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='show_all_content',
        ),
    ]
