# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0027_auto_20170411_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='like_or',
        ),
    ]
