# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0028_remove_answer_like_or'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_reply_input',
        ),
    ]
