# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0029_remove_comment_comment_reply_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='child_comment',
            new_name='child_comments',
        ),
    ]
