# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0030_auto_20170412_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='child_comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='site_page.Comment'),
        ),
    ]
