# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0031_auto_20170412_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='give_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='site_page.Answer'),
        ),
    ]
